//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\namofun\plagiarism\src\Plag.Frontend.Csharp\CSharpPreprocessorParser.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Antlr4.Grammar.Csharp {
 using System.Linq; 
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
//[System.CLSCompliant(false)]
public partial class CSharpPreprocessorParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		BYTE_ORDER_MARK=1, SINGLE_LINE_DOC_COMMENT=2, DELIMITED_DOC_COMMENT=3, 
		SINGLE_LINE_COMMENT=4, DELIMITED_COMMENT=5, WHITESPACES=6, SHARP=7, ABSTRACT=8, 
		ADD=9, ALIAS=10, ARGLIST=11, AS=12, ASCENDING=13, ASYNC=14, AWAIT=15, 
		BASE=16, BOOL=17, BREAK=18, BY=19, BYTE=20, CASE=21, CATCH=22, CHAR=23, 
		CHECKED=24, CLASS=25, CONST=26, CONTINUE=27, DECIMAL=28, DEFAULT=29, DELEGATE=30, 
		DESCENDING=31, DO=32, DOUBLE=33, DYNAMIC=34, ELSE=35, ENUM=36, EQUALS=37, 
		EVENT=38, EXPLICIT=39, EXTERN=40, FALSE=41, FINALLY=42, FIXED=43, FLOAT=44, 
		FOR=45, FOREACH=46, FROM=47, GET=48, GOTO=49, GROUP=50, IF=51, IMPLICIT=52, 
		IN=53, INT=54, INTERFACE=55, INTERNAL=56, INTO=57, IS=58, JOIN=59, LET=60, 
		LOCK=61, LONG=62, NAMEOF=63, NAMESPACE=64, NEW=65, NULL=66, OBJECT=67, 
		ON=68, OPERATOR=69, ORDERBY=70, OUT=71, OVERRIDE=72, PARAMS=73, PARTIAL=74, 
		PRIVATE=75, PROTECTED=76, PUBLIC=77, READONLY=78, REF=79, REMOVE=80, RETURN=81, 
		SBYTE=82, SEALED=83, SELECT=84, SET=85, SHORT=86, SIZEOF=87, STACKALLOC=88, 
		STATIC=89, STRING=90, STRUCT=91, SWITCH=92, THIS=93, THROW=94, TRUE=95, 
		TRY=96, TYPEOF=97, UINT=98, ULONG=99, UNCHECKED=100, UNMANAGED=101, UNSAFE=102, 
		USHORT=103, USING=104, VAR=105, VIRTUAL=106, VOID=107, VOLATILE=108, WHEN=109, 
		WHERE=110, WHILE=111, YIELD=112, IDENTIFIER=113, LITERAL_ACCESS=114, INTEGER_LITERAL=115, 
		HEX_INTEGER_LITERAL=116, BIN_INTEGER_LITERAL=117, REAL_LITERAL=118, CHARACTER_LITERAL=119, 
		REGULAR_STRING=120, VERBATIUM_STRING=121, INTERPOLATED_REGULAR_STRING_START=122, 
		INTERPOLATED_VERBATIUM_STRING_START=123, OPEN_BRACE=124, CLOSE_BRACE=125, 
		OPEN_BRACKET=126, CLOSE_BRACKET=127, OPEN_PARENS=128, CLOSE_PARENS=129, 
		DOT=130, COMMA=131, COLON=132, SEMICOLON=133, PLUS=134, MINUS=135, STAR=136, 
		DIV=137, PERCENT=138, AMP=139, BITWISE_OR=140, CARET=141, BANG=142, TILDE=143, 
		ASSIGNMENT=144, LT=145, GT=146, INTERR=147, DOUBLE_COLON=148, OP_COALESCING=149, 
		OP_INC=150, OP_DEC=151, OP_AND=152, OP_OR=153, OP_PTR=154, OP_EQ=155, 
		OP_NE=156, OP_LE=157, OP_GE=158, OP_ADD_ASSIGNMENT=159, OP_SUB_ASSIGNMENT=160, 
		OP_MULT_ASSIGNMENT=161, OP_DIV_ASSIGNMENT=162, OP_MOD_ASSIGNMENT=163, 
		OP_AND_ASSIGNMENT=164, OP_OR_ASSIGNMENT=165, OP_XOR_ASSIGNMENT=166, OP_LEFT_SHIFT=167, 
		OP_LEFT_SHIFT_ASSIGNMENT=168, OP_COALESCING_ASSIGNMENT=169, OP_RANGE=170, 
		DOUBLE_CURLY_INSIDE=171, OPEN_BRACE_INSIDE=172, REGULAR_CHAR_INSIDE=173, 
		VERBATIUM_DOUBLE_QUOTE_INSIDE=174, DOUBLE_QUOTE_INSIDE=175, REGULAR_STRING_INSIDE=176, 
		VERBATIUM_INSIDE_STRING=177, CLOSE_BRACE_INSIDE=178, FORMAT_STRING=179, 
		DIRECTIVE_WHITESPACES=180, DIGITS=181, DEFINE=182, UNDEF=183, ELIF=184, 
		ENDIF=185, LINE=186, ERROR=187, WARNING=188, REGION=189, ENDREGION=190, 
		PRAGMA=191, NULLABLE=192, DIRECTIVE_HIDDEN=193, CONDITIONAL_SYMBOL=194, 
		DIRECTIVE_NEW_LINE=195, TEXT=196, DOUBLE_CURLY_CLOSE_INSIDE=197;
	public const int
		RULE_preprocessorDirective = 0, RULE_directiveNewLineOrSharp = 1, RULE_preprocessorExpression = 2;
	public static readonly string[] ruleNames = {
		"preprocessorDirective", "directiveNewLineOrSharp", "preprocessorExpression"
	};

	private static readonly string[] _LiteralNames = {
		null, "'\u00EF\u00BB\u00BF'", null, null, null, null, null, "'#'", "'abstract'", 
		"'add'", "'alias'", "'__arglist'", "'as'", "'ascending'", "'async'", "'await'", 
		"'base'", "'bool'", "'break'", "'by'", "'byte'", "'case'", "'catch'", 
		"'char'", "'checked'", "'class'", "'const'", "'continue'", "'decimal'", 
		"'default'", "'delegate'", "'descending'", "'do'", "'double'", "'dynamic'", 
		"'else'", "'enum'", "'equals'", "'event'", "'explicit'", "'extern'", "'false'", 
		"'finally'", "'fixed'", "'float'", "'for'", "'foreach'", "'from'", "'get'", 
		"'goto'", "'group'", "'if'", "'implicit'", "'in'", "'int'", "'interface'", 
		"'internal'", "'into'", "'is'", "'join'", "'let'", "'lock'", "'long'", 
		"'nameof'", "'namespace'", "'new'", "'null'", "'object'", "'on'", "'operator'", 
		"'orderby'", "'out'", "'override'", "'params'", "'partial'", "'private'", 
		"'protected'", "'public'", "'readonly'", "'ref'", "'remove'", "'return'", 
		"'sbyte'", "'sealed'", "'select'", "'set'", "'short'", "'sizeof'", "'stackalloc'", 
		"'static'", "'string'", "'struct'", "'switch'", "'this'", "'throw'", "'true'", 
		"'try'", "'typeof'", "'uint'", "'ulong'", "'unchecked'", "'unmanaged'", 
		"'unsafe'", "'ushort'", "'using'", "'var'", "'virtual'", "'void'", "'volatile'", 
		"'when'", "'where'", "'while'", "'yield'", null, null, null, null, null, 
		null, null, null, null, null, null, "'{'", "'}'", "'['", "']'", "'('", 
		"')'", "'.'", "','", "':'", "';'", "'+'", "'-'", "'*'", "'/'", "'%'", 
		"'&'", "'|'", "'^'", "'!'", "'~'", "'='", "'<'", "'>'", "'?'", "'::'", 
		"'??'", "'++'", "'--'", "'&&'", "'||'", "'->'", "'=='", "'!='", "'<='", 
		"'>='", "'+='", "'-='", "'*='", "'/='", "'%='", "'&='", "'|='", "'^='", 
		"'<<'", "'<<='", "'??='", "'..'", "'{{'", null, null, null, null, null, 
		null, null, null, null, null, "'define'", "'undef'", "'elif'", "'endif'", 
		"'line'", null, null, null, null, null, null, "'hidden'", null, null, 
		null, "'}}'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "BYTE_ORDER_MARK", "SINGLE_LINE_DOC_COMMENT", "DELIMITED_DOC_COMMENT", 
		"SINGLE_LINE_COMMENT", "DELIMITED_COMMENT", "WHITESPACES", "SHARP", "ABSTRACT", 
		"ADD", "ALIAS", "ARGLIST", "AS", "ASCENDING", "ASYNC", "AWAIT", "BASE", 
		"BOOL", "BREAK", "BY", "BYTE", "CASE", "CATCH", "CHAR", "CHECKED", "CLASS", 
		"CONST", "CONTINUE", "DECIMAL", "DEFAULT", "DELEGATE", "DESCENDING", "DO", 
		"DOUBLE", "DYNAMIC", "ELSE", "ENUM", "EQUALS", "EVENT", "EXPLICIT", "EXTERN", 
		"FALSE", "FINALLY", "FIXED", "FLOAT", "FOR", "FOREACH", "FROM", "GET", 
		"GOTO", "GROUP", "IF", "IMPLICIT", "IN", "INT", "INTERFACE", "INTERNAL", 
		"INTO", "IS", "JOIN", "LET", "LOCK", "LONG", "NAMEOF", "NAMESPACE", "NEW", 
		"NULL", "OBJECT", "ON", "OPERATOR", "ORDERBY", "OUT", "OVERRIDE", "PARAMS", 
		"PARTIAL", "PRIVATE", "PROTECTED", "PUBLIC", "READONLY", "REF", "REMOVE", 
		"RETURN", "SBYTE", "SEALED", "SELECT", "SET", "SHORT", "SIZEOF", "STACKALLOC", 
		"STATIC", "STRING", "STRUCT", "SWITCH", "THIS", "THROW", "TRUE", "TRY", 
		"TYPEOF", "UINT", "ULONG", "UNCHECKED", "UNMANAGED", "UNSAFE", "USHORT", 
		"USING", "VAR", "VIRTUAL", "VOID", "VOLATILE", "WHEN", "WHERE", "WHILE", 
		"YIELD", "IDENTIFIER", "LITERAL_ACCESS", "INTEGER_LITERAL", "HEX_INTEGER_LITERAL", 
		"BIN_INTEGER_LITERAL", "REAL_LITERAL", "CHARACTER_LITERAL", "REGULAR_STRING", 
		"VERBATIUM_STRING", "INTERPOLATED_REGULAR_STRING_START", "INTERPOLATED_VERBATIUM_STRING_START", 
		"OPEN_BRACE", "CLOSE_BRACE", "OPEN_BRACKET", "CLOSE_BRACKET", "OPEN_PARENS", 
		"CLOSE_PARENS", "DOT", "COMMA", "COLON", "SEMICOLON", "PLUS", "MINUS", 
		"STAR", "DIV", "PERCENT", "AMP", "BITWISE_OR", "CARET", "BANG", "TILDE", 
		"ASSIGNMENT", "LT", "GT", "INTERR", "DOUBLE_COLON", "OP_COALESCING", "OP_INC", 
		"OP_DEC", "OP_AND", "OP_OR", "OP_PTR", "OP_EQ", "OP_NE", "OP_LE", "OP_GE", 
		"OP_ADD_ASSIGNMENT", "OP_SUB_ASSIGNMENT", "OP_MULT_ASSIGNMENT", "OP_DIV_ASSIGNMENT", 
		"OP_MOD_ASSIGNMENT", "OP_AND_ASSIGNMENT", "OP_OR_ASSIGNMENT", "OP_XOR_ASSIGNMENT", 
		"OP_LEFT_SHIFT", "OP_LEFT_SHIFT_ASSIGNMENT", "OP_COALESCING_ASSIGNMENT", 
		"OP_RANGE", "DOUBLE_CURLY_INSIDE", "OPEN_BRACE_INSIDE", "REGULAR_CHAR_INSIDE", 
		"VERBATIUM_DOUBLE_QUOTE_INSIDE", "DOUBLE_QUOTE_INSIDE", "REGULAR_STRING_INSIDE", 
		"VERBATIUM_INSIDE_STRING", "CLOSE_BRACE_INSIDE", "FORMAT_STRING", "DIRECTIVE_WHITESPACES", 
		"DIGITS", "DEFINE", "UNDEF", "ELIF", "ENDIF", "LINE", "ERROR", "WARNING", 
		"REGION", "ENDREGION", "PRAGMA", "NULLABLE", "DIRECTIVE_HIDDEN", "CONDITIONAL_SYMBOL", 
		"DIRECTIVE_NEW_LINE", "TEXT", "DOUBLE_CURLY_CLOSE_INSIDE"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "CSharpPreprocessorParser.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static CSharpPreprocessorParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

	Stack<bool> conditions = new Stack<bool>(new bool[] { true });
	public HashSet<string> ConditionalSymbols = new HashSet<string>() { "DEBUG" };
		public CSharpPreprocessorParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public CSharpPreprocessorParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class PreprocessorDirectiveContext : ParserRuleContext {
		public bool value;
		public PreprocessorDirectiveContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_preprocessorDirective; } }
		public string RuleName { get { return "PreprocessorDirective"; } }
	 
		public PreprocessorDirectiveContext() { }
		public virtual void CopyFrom(PreprocessorDirectiveContext context) {
			base.CopyFrom(context);
			this.value = context.value;
		}
	}
	public partial class PreprocessorDiagnosticContext : PreprocessorDirectiveContext {
		public ITerminalNode ERROR() { return GetToken(CSharpPreprocessorParser.ERROR, 0); }
		public ITerminalNode TEXT() { return GetToken(CSharpPreprocessorParser.TEXT, 0); }
		public DirectiveNewLineOrSharpContext directiveNewLineOrSharp() {
			return GetRuleContext<DirectiveNewLineOrSharpContext>(0);
		}
		public ITerminalNode WARNING() { return GetToken(CSharpPreprocessorParser.WARNING, 0); }
		public PreprocessorDiagnosticContext(PreprocessorDirectiveContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ICSharpPreprocessorParserListener typedListener = listener as ICSharpPreprocessorParserListener;
			if (typedListener != null) typedListener.EnterPreprocessorDiagnostic(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICSharpPreprocessorParserListener typedListener = listener as ICSharpPreprocessorParserListener;
			if (typedListener != null) typedListener.ExitPreprocessorDiagnostic(this);
		}
	}
	public partial class PreprocessorNullableContext : PreprocessorDirectiveContext {
		public ITerminalNode NULLABLE() { return GetToken(CSharpPreprocessorParser.NULLABLE, 0); }
		public ITerminalNode TEXT() { return GetToken(CSharpPreprocessorParser.TEXT, 0); }
		public DirectiveNewLineOrSharpContext directiveNewLineOrSharp() {
			return GetRuleContext<DirectiveNewLineOrSharpContext>(0);
		}
		public PreprocessorNullableContext(PreprocessorDirectiveContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ICSharpPreprocessorParserListener typedListener = listener as ICSharpPreprocessorParserListener;
			if (typedListener != null) typedListener.EnterPreprocessorNullable(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICSharpPreprocessorParserListener typedListener = listener as ICSharpPreprocessorParserListener;
			if (typedListener != null) typedListener.ExitPreprocessorNullable(this);
		}
	}
	public partial class PreprocessorRegionContext : PreprocessorDirectiveContext {
		public ITerminalNode REGION() { return GetToken(CSharpPreprocessorParser.REGION, 0); }
		public DirectiveNewLineOrSharpContext directiveNewLineOrSharp() {
			return GetRuleContext<DirectiveNewLineOrSharpContext>(0);
		}
		public ITerminalNode TEXT() { return GetToken(CSharpPreprocessorParser.TEXT, 0); }
		public ITerminalNode ENDREGION() { return GetToken(CSharpPreprocessorParser.ENDREGION, 0); }
		public PreprocessorRegionContext(PreprocessorDirectiveContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ICSharpPreprocessorParserListener typedListener = listener as ICSharpPreprocessorParserListener;
			if (typedListener != null) typedListener.EnterPreprocessorRegion(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICSharpPreprocessorParserListener typedListener = listener as ICSharpPreprocessorParserListener;
			if (typedListener != null) typedListener.ExitPreprocessorRegion(this);
		}
	}
	public partial class PreprocessorDeclarationContext : PreprocessorDirectiveContext {
		public IToken _CONDITIONAL_SYMBOL;
		public ITerminalNode DEFINE() { return GetToken(CSharpPreprocessorParser.DEFINE, 0); }
		public ITerminalNode CONDITIONAL_SYMBOL() { return GetToken(CSharpPreprocessorParser.CONDITIONAL_SYMBOL, 0); }
		public DirectiveNewLineOrSharpContext directiveNewLineOrSharp() {
			return GetRuleContext<DirectiveNewLineOrSharpContext>(0);
		}
		public ITerminalNode UNDEF() { return GetToken(CSharpPreprocessorParser.UNDEF, 0); }
		public PreprocessorDeclarationContext(PreprocessorDirectiveContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ICSharpPreprocessorParserListener typedListener = listener as ICSharpPreprocessorParserListener;
			if (typedListener != null) typedListener.EnterPreprocessorDeclaration(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICSharpPreprocessorParserListener typedListener = listener as ICSharpPreprocessorParserListener;
			if (typedListener != null) typedListener.ExitPreprocessorDeclaration(this);
		}
	}
	public partial class PreprocessorConditionalContext : PreprocessorDirectiveContext {
		public PreprocessorExpressionContext expr;
		public ITerminalNode IF() { return GetToken(CSharpPreprocessorParser.IF, 0); }
		public DirectiveNewLineOrSharpContext directiveNewLineOrSharp() {
			return GetRuleContext<DirectiveNewLineOrSharpContext>(0);
		}
		public PreprocessorExpressionContext preprocessorExpression() {
			return GetRuleContext<PreprocessorExpressionContext>(0);
		}
		public ITerminalNode ELIF() { return GetToken(CSharpPreprocessorParser.ELIF, 0); }
		public ITerminalNode ELSE() { return GetToken(CSharpPreprocessorParser.ELSE, 0); }
		public ITerminalNode ENDIF() { return GetToken(CSharpPreprocessorParser.ENDIF, 0); }
		public PreprocessorConditionalContext(PreprocessorDirectiveContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ICSharpPreprocessorParserListener typedListener = listener as ICSharpPreprocessorParserListener;
			if (typedListener != null) typedListener.EnterPreprocessorConditional(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICSharpPreprocessorParserListener typedListener = listener as ICSharpPreprocessorParserListener;
			if (typedListener != null) typedListener.ExitPreprocessorConditional(this);
		}
	}
	public partial class PreprocessorPragmaContext : PreprocessorDirectiveContext {
		public ITerminalNode PRAGMA() { return GetToken(CSharpPreprocessorParser.PRAGMA, 0); }
		public ITerminalNode TEXT() { return GetToken(CSharpPreprocessorParser.TEXT, 0); }
		public DirectiveNewLineOrSharpContext directiveNewLineOrSharp() {
			return GetRuleContext<DirectiveNewLineOrSharpContext>(0);
		}
		public PreprocessorPragmaContext(PreprocessorDirectiveContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ICSharpPreprocessorParserListener typedListener = listener as ICSharpPreprocessorParserListener;
			if (typedListener != null) typedListener.EnterPreprocessorPragma(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICSharpPreprocessorParserListener typedListener = listener as ICSharpPreprocessorParserListener;
			if (typedListener != null) typedListener.ExitPreprocessorPragma(this);
		}
	}
	public partial class PreprocessorLineContext : PreprocessorDirectiveContext {
		public ITerminalNode LINE() { return GetToken(CSharpPreprocessorParser.LINE, 0); }
		public DirectiveNewLineOrSharpContext directiveNewLineOrSharp() {
			return GetRuleContext<DirectiveNewLineOrSharpContext>(0);
		}
		public ITerminalNode DIGITS() { return GetToken(CSharpPreprocessorParser.DIGITS, 0); }
		public ITerminalNode DEFAULT() { return GetToken(CSharpPreprocessorParser.DEFAULT, 0); }
		public ITerminalNode DIRECTIVE_HIDDEN() { return GetToken(CSharpPreprocessorParser.DIRECTIVE_HIDDEN, 0); }
		public ITerminalNode STRING() { return GetToken(CSharpPreprocessorParser.STRING, 0); }
		public PreprocessorLineContext(PreprocessorDirectiveContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ICSharpPreprocessorParserListener typedListener = listener as ICSharpPreprocessorParserListener;
			if (typedListener != null) typedListener.EnterPreprocessorLine(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICSharpPreprocessorParserListener typedListener = listener as ICSharpPreprocessorParserListener;
			if (typedListener != null) typedListener.ExitPreprocessorLine(this);
		}
	}

	[RuleVersion(0)]
	public PreprocessorDirectiveContext PreprocessorDirective() {
		PreprocessorDirectiveContext _localctx = new PreprocessorDirectiveContext(Context, State);
		EnterRule(_localctx, 0, RULE_preprocessorDirective);
		int _la;
		try {
			State = 80;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case DEFINE:
				_localctx = new PreprocessorDeclarationContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 6; Match(DEFINE);
				State = 7; ((PreprocessorDeclarationContext)_localctx)._CONDITIONAL_SYMBOL = Match(CONDITIONAL_SYMBOL);
				State = 8; DirectiveNewLineOrSharp();
				 ConditionalSymbols.Add((((PreprocessorDeclarationContext)_localctx)._CONDITIONAL_SYMBOL!=null?((PreprocessorDeclarationContext)_localctx)._CONDITIONAL_SYMBOL.Text:null));
					   ((PreprocessorDeclarationContext)_localctx).value =  conditions.All(c => c); 
				}
				break;
			case UNDEF:
				_localctx = new PreprocessorDeclarationContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 11; Match(UNDEF);
				State = 12; ((PreprocessorDeclarationContext)_localctx)._CONDITIONAL_SYMBOL = Match(CONDITIONAL_SYMBOL);
				State = 13; DirectiveNewLineOrSharp();
				 ConditionalSymbols.Remove((((PreprocessorDeclarationContext)_localctx)._CONDITIONAL_SYMBOL!=null?((PreprocessorDeclarationContext)_localctx)._CONDITIONAL_SYMBOL.Text:null));
					   ((PreprocessorDeclarationContext)_localctx).value =  conditions.All(c => c); 
				}
				break;
			case IF:
				_localctx = new PreprocessorConditionalContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 16; Match(IF);
				State = 17; ((PreprocessorConditionalContext)_localctx).expr = PreprocessorExpression(0);
				State = 18; DirectiveNewLineOrSharp();
				 ((PreprocessorConditionalContext)_localctx).value =  ((PreprocessorConditionalContext)_localctx).expr.value == "true" && conditions.All(c => c); conditions.Push(((PreprocessorConditionalContext)_localctx).expr.value == "true"); 
				}
				break;
			case ELIF:
				_localctx = new PreprocessorConditionalContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 21; Match(ELIF);
				State = 22; ((PreprocessorConditionalContext)_localctx).expr = PreprocessorExpression(0);
				State = 23; DirectiveNewLineOrSharp();
				 if (!conditions.Peek()) { conditions.Pop(); ((PreprocessorConditionalContext)_localctx).value =  ((PreprocessorConditionalContext)_localctx).expr.value == "true" && conditions.All(c => c);
					     conditions.Push(((PreprocessorConditionalContext)_localctx).expr.value == "true"); } else ((PreprocessorConditionalContext)_localctx).value =  false; 
				}
				break;
			case ELSE:
				_localctx = new PreprocessorConditionalContext(_localctx);
				EnterOuterAlt(_localctx, 5);
				{
				State = 26; Match(ELSE);
				State = 27; DirectiveNewLineOrSharp();
				 if (!conditions.Peek()) { conditions.Pop(); ((PreprocessorConditionalContext)_localctx).value =  true && conditions.All(c => c); conditions.Push(true); }
					    else ((PreprocessorConditionalContext)_localctx).value =  false; 
				}
				break;
			case ENDIF:
				_localctx = new PreprocessorConditionalContext(_localctx);
				EnterOuterAlt(_localctx, 6);
				{
				State = 30; Match(ENDIF);
				State = 31; DirectiveNewLineOrSharp();
				 conditions.Pop(); ((PreprocessorConditionalContext)_localctx).value =  conditions.Peek(); 
				}
				break;
			case LINE:
				_localctx = new PreprocessorLineContext(_localctx);
				EnterOuterAlt(_localctx, 7);
				{
				State = 34; Match(LINE);
				State = 41;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case DIGITS:
					{
					State = 35; Match(DIGITS);
					State = 37;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					if (_la==STRING) {
						{
						State = 36; Match(STRING);
						}
					}

					}
					break;
				case DEFAULT:
					{
					State = 39; Match(DEFAULT);
					}
					break;
				case DIRECTIVE_HIDDEN:
					{
					State = 40; Match(DIRECTIVE_HIDDEN);
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 43; DirectiveNewLineOrSharp();
				 ((PreprocessorLineContext)_localctx).value =  conditions.All(c => c); 
				}
				break;
			case ERROR:
				_localctx = new PreprocessorDiagnosticContext(_localctx);
				EnterOuterAlt(_localctx, 8);
				{
				State = 46; Match(ERROR);
				State = 47; Match(TEXT);
				State = 48; DirectiveNewLineOrSharp();
				 ((PreprocessorDiagnosticContext)_localctx).value =  conditions.All(c => c); 
				}
				break;
			case WARNING:
				_localctx = new PreprocessorDiagnosticContext(_localctx);
				EnterOuterAlt(_localctx, 9);
				{
				State = 51; Match(WARNING);
				State = 52; Match(TEXT);
				State = 53; DirectiveNewLineOrSharp();
				 ((PreprocessorDiagnosticContext)_localctx).value =  conditions.All(c => c); 
				}
				break;
			case REGION:
				_localctx = new PreprocessorRegionContext(_localctx);
				EnterOuterAlt(_localctx, 10);
				{
				State = 56; Match(REGION);
				State = 58;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==TEXT) {
					{
					State = 57; Match(TEXT);
					}
				}

				State = 60; DirectiveNewLineOrSharp();
				 ((PreprocessorRegionContext)_localctx).value =  conditions.All(c => c); 
				}
				break;
			case ENDREGION:
				_localctx = new PreprocessorRegionContext(_localctx);
				EnterOuterAlt(_localctx, 11);
				{
				State = 63; Match(ENDREGION);
				State = 65;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==TEXT) {
					{
					State = 64; Match(TEXT);
					}
				}

				State = 67; DirectiveNewLineOrSharp();
				 ((PreprocessorRegionContext)_localctx).value =  conditions.All(c => c); 
				}
				break;
			case PRAGMA:
				_localctx = new PreprocessorPragmaContext(_localctx);
				EnterOuterAlt(_localctx, 12);
				{
				State = 70; Match(PRAGMA);
				State = 71; Match(TEXT);
				State = 72; DirectiveNewLineOrSharp();
				 ((PreprocessorPragmaContext)_localctx).value =  conditions.All(c => c); 
				}
				break;
			case NULLABLE:
				_localctx = new PreprocessorNullableContext(_localctx);
				EnterOuterAlt(_localctx, 13);
				{
				State = 75; Match(NULLABLE);
				State = 76; Match(TEXT);
				State = 77; DirectiveNewLineOrSharp();
				 ((PreprocessorNullableContext)_localctx).value =  conditions.All(c => c); 
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DirectiveNewLineOrSharpContext : ParserRuleContext {
		public ITerminalNode DIRECTIVE_NEW_LINE() { return GetToken(CSharpPreprocessorParser.DIRECTIVE_NEW_LINE, 0); }
		public ITerminalNode Eof() { return GetToken(CSharpPreprocessorParser.Eof, 0); }
		public DirectiveNewLineOrSharpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_directiveNewLineOrSharp; } }
		public string RuleName { get { return "DirectiveNewLineOrSharp"; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICSharpPreprocessorParserListener typedListener = listener as ICSharpPreprocessorParserListener;
			if (typedListener != null) typedListener.EnterDirectiveNewLineOrSharp(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICSharpPreprocessorParserListener typedListener = listener as ICSharpPreprocessorParserListener;
			if (typedListener != null) typedListener.ExitDirectiveNewLineOrSharp(this);
		}
	}

	[RuleVersion(0)]
	public DirectiveNewLineOrSharpContext DirectiveNewLineOrSharp() {
		DirectiveNewLineOrSharpContext _localctx = new DirectiveNewLineOrSharpContext(Context, State);
		EnterRule(_localctx, 2, RULE_directiveNewLineOrSharp);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 82;
			_la = TokenStream.LA(1);
			if ( !(_la==Eof || _la==DIRECTIVE_NEW_LINE) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PreprocessorExpressionContext : ParserRuleContext {
		public string value;
		public PreprocessorExpressionContext expr1;
		public IToken _CONDITIONAL_SYMBOL;
		public PreprocessorExpressionContext expr;
		public PreprocessorExpressionContext expr2;
		public ITerminalNode TRUE() { return GetToken(CSharpPreprocessorParser.TRUE, 0); }
		public ITerminalNode FALSE() { return GetToken(CSharpPreprocessorParser.FALSE, 0); }
		public ITerminalNode CONDITIONAL_SYMBOL() { return GetToken(CSharpPreprocessorParser.CONDITIONAL_SYMBOL, 0); }
		public ITerminalNode OPEN_PARENS() { return GetToken(CSharpPreprocessorParser.OPEN_PARENS, 0); }
		public ITerminalNode CLOSE_PARENS() { return GetToken(CSharpPreprocessorParser.CLOSE_PARENS, 0); }
		public PreprocessorExpressionContext[] preprocessorExpression() {
			return GetRuleContexts<PreprocessorExpressionContext>();
		}
		public PreprocessorExpressionContext preprocessorExpression(int i) {
			return GetRuleContext<PreprocessorExpressionContext>(i);
		}
		public ITerminalNode BANG() { return GetToken(CSharpPreprocessorParser.BANG, 0); }
		public ITerminalNode OP_EQ() { return GetToken(CSharpPreprocessorParser.OP_EQ, 0); }
		public ITerminalNode OP_NE() { return GetToken(CSharpPreprocessorParser.OP_NE, 0); }
		public ITerminalNode OP_AND() { return GetToken(CSharpPreprocessorParser.OP_AND, 0); }
		public ITerminalNode OP_OR() { return GetToken(CSharpPreprocessorParser.OP_OR, 0); }
		public PreprocessorExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_preprocessorExpression; } }
		public string RuleName { get { return "PreprocessorExpression"; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICSharpPreprocessorParserListener typedListener = listener as ICSharpPreprocessorParserListener;
			if (typedListener != null) typedListener.EnterPreprocessorExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICSharpPreprocessorParserListener typedListener = listener as ICSharpPreprocessorParserListener;
			if (typedListener != null) typedListener.ExitPreprocessorExpression(this);
		}
	}

	[RuleVersion(0)]
	public PreprocessorExpressionContext PreprocessorExpression() {
		return PreprocessorExpression(0);
	}

	private PreprocessorExpressionContext PreprocessorExpression(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		PreprocessorExpressionContext _localctx = new PreprocessorExpressionContext(Context, _parentState);
		PreprocessorExpressionContext _prevctx = _localctx;
		int _startState = 4;
		EnterRecursionRule(_localctx, 4, RULE_preprocessorExpression, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 100;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case TRUE:
				{
				State = 85; Match(TRUE);
				 _localctx.value =  "true"; 
				}
				break;
			case FALSE:
				{
				State = 87; Match(FALSE);
				 _localctx.value =  "false"; 
				}
				break;
			case CONDITIONAL_SYMBOL:
				{
				State = 89; _localctx._CONDITIONAL_SYMBOL = Match(CONDITIONAL_SYMBOL);
				 _localctx.value =  ConditionalSymbols.Contains((_localctx._CONDITIONAL_SYMBOL!=null?_localctx._CONDITIONAL_SYMBOL.Text:null)) ? "true" : "false"; 
				}
				break;
			case OPEN_PARENS:
				{
				State = 91; Match(OPEN_PARENS);
				State = 92; _localctx.expr = PreprocessorExpression(0);
				State = 93; Match(CLOSE_PARENS);
				 _localctx.value =  _localctx.expr.value; 
				}
				break;
			case BANG:
				{
				State = 96; Match(BANG);
				State = 97; _localctx.expr = PreprocessorExpression(5);
				 _localctx.value =  _localctx.expr.value == "true" ? "false" : "true"; 
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 124;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,7,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 122;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,6,Context) ) {
					case 1:
						{
						_localctx = new PreprocessorExpressionContext(_parentctx, _parentState);
						_localctx.expr1 = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_preprocessorExpression);
						State = 102;
						if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
						State = 103; Match(OP_EQ);
						State = 104; _localctx.expr2 = PreprocessorExpression(5);
						 _localctx.value =  (_localctx.expr1.value == _localctx.expr2.value ? "true" : "false"); 
						}
						break;
					case 2:
						{
						_localctx = new PreprocessorExpressionContext(_parentctx, _parentState);
						_localctx.expr1 = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_preprocessorExpression);
						State = 107;
						if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
						State = 108; Match(OP_NE);
						State = 109; _localctx.expr2 = PreprocessorExpression(4);
						 _localctx.value =  (_localctx.expr1.value != _localctx.expr2.value ? "true" : "false"); 
						}
						break;
					case 3:
						{
						_localctx = new PreprocessorExpressionContext(_parentctx, _parentState);
						_localctx.expr1 = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_preprocessorExpression);
						State = 112;
						if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
						State = 113; Match(OP_AND);
						State = 114; _localctx.expr2 = PreprocessorExpression(3);
						 _localctx.value =  (_localctx.expr1.value == "true" && _localctx.expr2.value == "true" ? "true" : "false"); 
						}
						break;
					case 4:
						{
						_localctx = new PreprocessorExpressionContext(_parentctx, _parentState);
						_localctx.expr1 = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_preprocessorExpression);
						State = 117;
						if (!(Precpred(Context, 1))) throw new FailedPredicateException(this, "Precpred(Context, 1)");
						State = 118; Match(OP_OR);
						State = 119; _localctx.expr2 = PreprocessorExpression(2);
						 _localctx.value =  (_localctx.expr1.value == "true" || _localctx.expr2.value == "true" ? "true" : "false"); 
						}
						break;
					}
					} 
				}
				State = 126;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,7,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 2: return preprocessorExpression_sempred((PreprocessorExpressionContext)_localctx, predIndex);
		}
		return true;
	}
	private bool preprocessorExpression_sempred(PreprocessorExpressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 4);
		case 1: return Precpred(Context, 3);
		case 2: return Precpred(Context, 2);
		case 3: return Precpred(Context, 1);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\xC7', '\x82', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x5', '\x2', '(', '\n', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x5', '\x2', ',', '\n', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x5', 
		'\x2', '=', '\n', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x5', '\x2', '\x44', '\n', '\x2', '\x3', '\x2', 
		'\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', 
		'\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', 
		'\x3', '\x2', '\x3', '\x2', '\x5', '\x2', 'S', '\n', '\x2', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x4', '\x5', '\x4', 'g', '\n', '\x4', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\a', '\x4', '}', 
		'\n', '\x4', '\f', '\x4', '\xE', '\x4', '\x80', '\v', '\x4', '\x3', '\x4', 
		'\x2', '\x3', '\x6', '\x5', '\x2', '\x4', '\x6', '\x2', '\x3', '\x3', 
		'\x3', '\xC5', '\xC5', '\x2', '\x97', '\x2', 'R', '\x3', '\x2', '\x2', 
		'\x2', '\x4', 'T', '\x3', '\x2', '\x2', '\x2', '\x6', '\x66', '\x3', '\x2', 
		'\x2', '\x2', '\b', '\t', '\a', '\xB8', '\x2', '\x2', '\t', '\n', '\a', 
		'\xC4', '\x2', '\x2', '\n', '\v', '\x5', '\x4', '\x3', '\x2', '\v', '\f', 
		'\b', '\x2', '\x1', '\x2', '\f', 'S', '\x3', '\x2', '\x2', '\x2', '\r', 
		'\xE', '\a', '\xB9', '\x2', '\x2', '\xE', '\xF', '\a', '\xC4', '\x2', 
		'\x2', '\xF', '\x10', '\x5', '\x4', '\x3', '\x2', '\x10', '\x11', '\b', 
		'\x2', '\x1', '\x2', '\x11', 'S', '\x3', '\x2', '\x2', '\x2', '\x12', 
		'\x13', '\a', '\x35', '\x2', '\x2', '\x13', '\x14', '\x5', '\x6', '\x4', 
		'\x2', '\x14', '\x15', '\x5', '\x4', '\x3', '\x2', '\x15', '\x16', '\b', 
		'\x2', '\x1', '\x2', '\x16', 'S', '\x3', '\x2', '\x2', '\x2', '\x17', 
		'\x18', '\a', '\xBA', '\x2', '\x2', '\x18', '\x19', '\x5', '\x6', '\x4', 
		'\x2', '\x19', '\x1A', '\x5', '\x4', '\x3', '\x2', '\x1A', '\x1B', '\b', 
		'\x2', '\x1', '\x2', '\x1B', 'S', '\x3', '\x2', '\x2', '\x2', '\x1C', 
		'\x1D', '\a', '%', '\x2', '\x2', '\x1D', '\x1E', '\x5', '\x4', '\x3', 
		'\x2', '\x1E', '\x1F', '\b', '\x2', '\x1', '\x2', '\x1F', 'S', '\x3', 
		'\x2', '\x2', '\x2', ' ', '!', '\a', '\xBB', '\x2', '\x2', '!', '\"', 
		'\x5', '\x4', '\x3', '\x2', '\"', '#', '\b', '\x2', '\x1', '\x2', '#', 
		'S', '\x3', '\x2', '\x2', '\x2', '$', '+', '\a', '\xBC', '\x2', '\x2', 
		'%', '\'', '\a', '\xB7', '\x2', '\x2', '&', '(', '\a', '\\', '\x2', '\x2', 
		'\'', '&', '\x3', '\x2', '\x2', '\x2', '\'', '(', '\x3', '\x2', '\x2', 
		'\x2', '(', ',', '\x3', '\x2', '\x2', '\x2', ')', ',', '\a', '\x1F', '\x2', 
		'\x2', '*', ',', '\a', '\xC3', '\x2', '\x2', '+', '%', '\x3', '\x2', '\x2', 
		'\x2', '+', ')', '\x3', '\x2', '\x2', '\x2', '+', '*', '\x3', '\x2', '\x2', 
		'\x2', ',', '-', '\x3', '\x2', '\x2', '\x2', '-', '.', '\x5', '\x4', '\x3', 
		'\x2', '.', '/', '\b', '\x2', '\x1', '\x2', '/', 'S', '\x3', '\x2', '\x2', 
		'\x2', '\x30', '\x31', '\a', '\xBD', '\x2', '\x2', '\x31', '\x32', '\a', 
		'\xC6', '\x2', '\x2', '\x32', '\x33', '\x5', '\x4', '\x3', '\x2', '\x33', 
		'\x34', '\b', '\x2', '\x1', '\x2', '\x34', 'S', '\x3', '\x2', '\x2', '\x2', 
		'\x35', '\x36', '\a', '\xBE', '\x2', '\x2', '\x36', '\x37', '\a', '\xC6', 
		'\x2', '\x2', '\x37', '\x38', '\x5', '\x4', '\x3', '\x2', '\x38', '\x39', 
		'\b', '\x2', '\x1', '\x2', '\x39', 'S', '\x3', '\x2', '\x2', '\x2', ':', 
		'<', '\a', '\xBF', '\x2', '\x2', ';', '=', '\a', '\xC6', '\x2', '\x2', 
		'<', ';', '\x3', '\x2', '\x2', '\x2', '<', '=', '\x3', '\x2', '\x2', '\x2', 
		'=', '>', '\x3', '\x2', '\x2', '\x2', '>', '?', '\x5', '\x4', '\x3', '\x2', 
		'?', '@', '\b', '\x2', '\x1', '\x2', '@', 'S', '\x3', '\x2', '\x2', '\x2', 
		'\x41', '\x43', '\a', '\xC0', '\x2', '\x2', '\x42', '\x44', '\a', '\xC6', 
		'\x2', '\x2', '\x43', '\x42', '\x3', '\x2', '\x2', '\x2', '\x43', '\x44', 
		'\x3', '\x2', '\x2', '\x2', '\x44', '\x45', '\x3', '\x2', '\x2', '\x2', 
		'\x45', '\x46', '\x5', '\x4', '\x3', '\x2', '\x46', 'G', '\b', '\x2', 
		'\x1', '\x2', 'G', 'S', '\x3', '\x2', '\x2', '\x2', 'H', 'I', '\a', '\xC1', 
		'\x2', '\x2', 'I', 'J', '\a', '\xC6', '\x2', '\x2', 'J', 'K', '\x5', '\x4', 
		'\x3', '\x2', 'K', 'L', '\b', '\x2', '\x1', '\x2', 'L', 'S', '\x3', '\x2', 
		'\x2', '\x2', 'M', 'N', '\a', '\xC2', '\x2', '\x2', 'N', 'O', '\a', '\xC6', 
		'\x2', '\x2', 'O', 'P', '\x5', '\x4', '\x3', '\x2', 'P', 'Q', '\b', '\x2', 
		'\x1', '\x2', 'Q', 'S', '\x3', '\x2', '\x2', '\x2', 'R', '\b', '\x3', 
		'\x2', '\x2', '\x2', 'R', '\r', '\x3', '\x2', '\x2', '\x2', 'R', '\x12', 
		'\x3', '\x2', '\x2', '\x2', 'R', '\x17', '\x3', '\x2', '\x2', '\x2', 'R', 
		'\x1C', '\x3', '\x2', '\x2', '\x2', 'R', ' ', '\x3', '\x2', '\x2', '\x2', 
		'R', '$', '\x3', '\x2', '\x2', '\x2', 'R', '\x30', '\x3', '\x2', '\x2', 
		'\x2', 'R', '\x35', '\x3', '\x2', '\x2', '\x2', 'R', ':', '\x3', '\x2', 
		'\x2', '\x2', 'R', '\x41', '\x3', '\x2', '\x2', '\x2', 'R', 'H', '\x3', 
		'\x2', '\x2', '\x2', 'R', 'M', '\x3', '\x2', '\x2', '\x2', 'S', '\x3', 
		'\x3', '\x2', '\x2', '\x2', 'T', 'U', '\t', '\x2', '\x2', '\x2', 'U', 
		'\x5', '\x3', '\x2', '\x2', '\x2', 'V', 'W', '\b', '\x4', '\x1', '\x2', 
		'W', 'X', '\a', '\x61', '\x2', '\x2', 'X', 'g', '\b', '\x4', '\x1', '\x2', 
		'Y', 'Z', '\a', '+', '\x2', '\x2', 'Z', 'g', '\b', '\x4', '\x1', '\x2', 
		'[', '\\', '\a', '\xC4', '\x2', '\x2', '\\', 'g', '\b', '\x4', '\x1', 
		'\x2', ']', '^', '\a', '\x82', '\x2', '\x2', '^', '_', '\x5', '\x6', '\x4', 
		'\x2', '_', '`', '\a', '\x83', '\x2', '\x2', '`', '\x61', '\b', '\x4', 
		'\x1', '\x2', '\x61', 'g', '\x3', '\x2', '\x2', '\x2', '\x62', '\x63', 
		'\a', '\x90', '\x2', '\x2', '\x63', '\x64', '\x5', '\x6', '\x4', '\a', 
		'\x64', '\x65', '\b', '\x4', '\x1', '\x2', '\x65', 'g', '\x3', '\x2', 
		'\x2', '\x2', '\x66', 'V', '\x3', '\x2', '\x2', '\x2', '\x66', 'Y', '\x3', 
		'\x2', '\x2', '\x2', '\x66', '[', '\x3', '\x2', '\x2', '\x2', '\x66', 
		']', '\x3', '\x2', '\x2', '\x2', '\x66', '\x62', '\x3', '\x2', '\x2', 
		'\x2', 'g', '~', '\x3', '\x2', '\x2', '\x2', 'h', 'i', '\f', '\x6', '\x2', 
		'\x2', 'i', 'j', '\a', '\x9D', '\x2', '\x2', 'j', 'k', '\x5', '\x6', '\x4', 
		'\a', 'k', 'l', '\b', '\x4', '\x1', '\x2', 'l', '}', '\x3', '\x2', '\x2', 
		'\x2', 'm', 'n', '\f', '\x5', '\x2', '\x2', 'n', 'o', '\a', '\x9E', '\x2', 
		'\x2', 'o', 'p', '\x5', '\x6', '\x4', '\x6', 'p', 'q', '\b', '\x4', '\x1', 
		'\x2', 'q', '}', '\x3', '\x2', '\x2', '\x2', 'r', 's', '\f', '\x4', '\x2', 
		'\x2', 's', 't', '\a', '\x9A', '\x2', '\x2', 't', 'u', '\x5', '\x6', '\x4', 
		'\x5', 'u', 'v', '\b', '\x4', '\x1', '\x2', 'v', '}', '\x3', '\x2', '\x2', 
		'\x2', 'w', 'x', '\f', '\x3', '\x2', '\x2', 'x', 'y', '\a', '\x9B', '\x2', 
		'\x2', 'y', 'z', '\x5', '\x6', '\x4', '\x4', 'z', '{', '\b', '\x4', '\x1', 
		'\x2', '{', '}', '\x3', '\x2', '\x2', '\x2', '|', 'h', '\x3', '\x2', '\x2', 
		'\x2', '|', 'm', '\x3', '\x2', '\x2', '\x2', '|', 'r', '\x3', '\x2', '\x2', 
		'\x2', '|', 'w', '\x3', '\x2', '\x2', '\x2', '}', '\x80', '\x3', '\x2', 
		'\x2', '\x2', '~', '|', '\x3', '\x2', '\x2', '\x2', '~', '\x7F', '\x3', 
		'\x2', '\x2', '\x2', '\x7F', '\a', '\x3', '\x2', '\x2', '\x2', '\x80', 
		'~', '\x3', '\x2', '\x2', '\x2', '\n', '\'', '+', '<', '\x43', 'R', '\x66', 
		'|', '~',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace Antlr4.Grammar.Csharp
