//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\namofun\plagiarism\src\Plag.Frontend.Python\Python3.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Antlr4.Grammar.Python {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IPython3Listener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
//[System.CLSCompliant(false)]
public partial class Python3BaseListener : IPython3Listener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.SingleInput"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSingleInput([NotNull] Python3Parser.SingleInputContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.SingleInput"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSingleInput([NotNull] Python3Parser.SingleInputContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.FileInput"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFileInput([NotNull] Python3Parser.FileInputContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.FileInput"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFileInput([NotNull] Python3Parser.FileInputContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.EvalInput"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEvalInput([NotNull] Python3Parser.EvalInputContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.EvalInput"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEvalInput([NotNull] Python3Parser.EvalInputContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.Decorator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDecorator([NotNull] Python3Parser.DecoratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.Decorator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDecorator([NotNull] Python3Parser.DecoratorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.Decorators"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDecorators([NotNull] Python3Parser.DecoratorsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.Decorators"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDecorators([NotNull] Python3Parser.DecoratorsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.Decorated"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDecorated([NotNull] Python3Parser.DecoratedContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.Decorated"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDecorated([NotNull] Python3Parser.DecoratedContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.AsyncFuncDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAsyncFuncDef([NotNull] Python3Parser.AsyncFuncDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.AsyncFuncDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAsyncFuncDef([NotNull] Python3Parser.AsyncFuncDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.Funcdef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncdef([NotNull] Python3Parser.FuncdefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.Funcdef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncdef([NotNull] Python3Parser.FuncdefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.Parameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameters([NotNull] Python3Parser.ParametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.Parameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameters([NotNull] Python3Parser.ParametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.Typedargslist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypedargslist([NotNull] Python3Parser.TypedargslistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.Typedargslist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypedargslist([NotNull] Python3Parser.TypedargslistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.Tfpdef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTfpdef([NotNull] Python3Parser.TfpdefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.Tfpdef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTfpdef([NotNull] Python3Parser.TfpdefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.Varargslist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarargslist([NotNull] Python3Parser.VarargslistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.Varargslist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarargslist([NotNull] Python3Parser.VarargslistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.Vfpdef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVfpdef([NotNull] Python3Parser.VfpdefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.Vfpdef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVfpdef([NotNull] Python3Parser.VfpdefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.Stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmt([NotNull] Python3Parser.StmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.Stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmt([NotNull] Python3Parser.StmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.SimpleStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimpleStmt([NotNull] Python3Parser.SimpleStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.SimpleStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimpleStmt([NotNull] Python3Parser.SimpleStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.SmallStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSmallStmt([NotNull] Python3Parser.SmallStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.SmallStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSmallStmt([NotNull] Python3Parser.SmallStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.ExprStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprStmt([NotNull] Python3Parser.ExprStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.ExprStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprStmt([NotNull] Python3Parser.ExprStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.AnnAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnnAssign([NotNull] Python3Parser.AnnAssignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.AnnAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnnAssign([NotNull] Python3Parser.AnnAssignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.TestlistStarExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTestlistStarExpr([NotNull] Python3Parser.TestlistStarExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.TestlistStarExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTestlistStarExpr([NotNull] Python3Parser.TestlistStarExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.AugAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAugAssign([NotNull] Python3Parser.AugAssignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.AugAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAugAssign([NotNull] Python3Parser.AugAssignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.DelStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDelStmt([NotNull] Python3Parser.DelStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.DelStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDelStmt([NotNull] Python3Parser.DelStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.PassStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPassStmt([NotNull] Python3Parser.PassStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.PassStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPassStmt([NotNull] Python3Parser.PassStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.FlowStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFlowStmt([NotNull] Python3Parser.FlowStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.FlowStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFlowStmt([NotNull] Python3Parser.FlowStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.BreakStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBreakStmt([NotNull] Python3Parser.BreakStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.BreakStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBreakStmt([NotNull] Python3Parser.BreakStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.ContinueStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterContinueStmt([NotNull] Python3Parser.ContinueStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.ContinueStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitContinueStmt([NotNull] Python3Parser.ContinueStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.ReturnStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnStmt([NotNull] Python3Parser.ReturnStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.ReturnStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnStmt([NotNull] Python3Parser.ReturnStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.YieldStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterYieldStmt([NotNull] Python3Parser.YieldStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.YieldStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitYieldStmt([NotNull] Python3Parser.YieldStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.RaiseStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRaiseStmt([NotNull] Python3Parser.RaiseStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.RaiseStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRaiseStmt([NotNull] Python3Parser.RaiseStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.ImportStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImportStmt([NotNull] Python3Parser.ImportStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.ImportStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImportStmt([NotNull] Python3Parser.ImportStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.ImportName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImportName([NotNull] Python3Parser.ImportNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.ImportName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImportName([NotNull] Python3Parser.ImportNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.ImportFrom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImportFrom([NotNull] Python3Parser.ImportFromContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.ImportFrom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImportFrom([NotNull] Python3Parser.ImportFromContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.ImportAsName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImportAsName([NotNull] Python3Parser.ImportAsNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.ImportAsName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImportAsName([NotNull] Python3Parser.ImportAsNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.DottedAsName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDottedAsName([NotNull] Python3Parser.DottedAsNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.DottedAsName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDottedAsName([NotNull] Python3Parser.DottedAsNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.ImportAsNames"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImportAsNames([NotNull] Python3Parser.ImportAsNamesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.ImportAsNames"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImportAsNames([NotNull] Python3Parser.ImportAsNamesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.DottedAsNames"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDottedAsNames([NotNull] Python3Parser.DottedAsNamesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.DottedAsNames"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDottedAsNames([NotNull] Python3Parser.DottedAsNamesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.DottedName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDottedName([NotNull] Python3Parser.DottedNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.DottedName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDottedName([NotNull] Python3Parser.DottedNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.GlobalStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGlobalStmt([NotNull] Python3Parser.GlobalStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.GlobalStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGlobalStmt([NotNull] Python3Parser.GlobalStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.NonLocalStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNonLocalStmt([NotNull] Python3Parser.NonLocalStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.NonLocalStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNonLocalStmt([NotNull] Python3Parser.NonLocalStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.AssertStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssertStmt([NotNull] Python3Parser.AssertStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.AssertStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssertStmt([NotNull] Python3Parser.AssertStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.CompoundStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompoundStmt([NotNull] Python3Parser.CompoundStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.CompoundStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompoundStmt([NotNull] Python3Parser.CompoundStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.AsyncStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAsyncStmt([NotNull] Python3Parser.AsyncStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.AsyncStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAsyncStmt([NotNull] Python3Parser.AsyncStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.IfStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStmt([NotNull] Python3Parser.IfStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.IfStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStmt([NotNull] Python3Parser.IfStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.WhileStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhileStmt([NotNull] Python3Parser.WhileStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.WhileStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhileStmt([NotNull] Python3Parser.WhileStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.ForStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForStmt([NotNull] Python3Parser.ForStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.ForStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForStmt([NotNull] Python3Parser.ForStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.TryStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTryStmt([NotNull] Python3Parser.TryStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.TryStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTryStmt([NotNull] Python3Parser.TryStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.WithStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWithStmt([NotNull] Python3Parser.WithStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.WithStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWithStmt([NotNull] Python3Parser.WithStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.WithItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWithItem([NotNull] Python3Parser.WithItemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.WithItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWithItem([NotNull] Python3Parser.WithItemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.ExceptClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExceptClause([NotNull] Python3Parser.ExceptClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.ExceptClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExceptClause([NotNull] Python3Parser.ExceptClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.Suite"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSuite([NotNull] Python3Parser.SuiteContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.Suite"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSuite([NotNull] Python3Parser.SuiteContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.Test"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTest([NotNull] Python3Parser.TestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.Test"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTest([NotNull] Python3Parser.TestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.TestNoCond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTestNoCond([NotNull] Python3Parser.TestNoCondContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.TestNoCond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTestNoCond([NotNull] Python3Parser.TestNoCondContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.Lambdef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLambdef([NotNull] Python3Parser.LambdefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.Lambdef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLambdef([NotNull] Python3Parser.LambdefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.LambdefNoCond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLambdefNoCond([NotNull] Python3Parser.LambdefNoCondContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.LambdefNoCond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLambdefNoCond([NotNull] Python3Parser.LambdefNoCondContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.OrTest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOrTest([NotNull] Python3Parser.OrTestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.OrTest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOrTest([NotNull] Python3Parser.OrTestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.AndTest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAndTest([NotNull] Python3Parser.AndTestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.AndTest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAndTest([NotNull] Python3Parser.AndTestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.NotTest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNotTest([NotNull] Python3Parser.NotTestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.NotTest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNotTest([NotNull] Python3Parser.NotTestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.Comparison"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComparison([NotNull] Python3Parser.ComparisonContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.Comparison"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComparison([NotNull] Python3Parser.ComparisonContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.CompOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompOp([NotNull] Python3Parser.CompOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.CompOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompOp([NotNull] Python3Parser.CompOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.StarExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStarExpr([NotNull] Python3Parser.StarExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.StarExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStarExpr([NotNull] Python3Parser.StarExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.Expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] Python3Parser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.Expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] Python3Parser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.XorExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterXorExpr([NotNull] Python3Parser.XorExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.XorExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitXorExpr([NotNull] Python3Parser.XorExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.AndExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAndExpr([NotNull] Python3Parser.AndExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.AndExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAndExpr([NotNull] Python3Parser.AndExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.ShiftExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShiftExpr([NotNull] Python3Parser.ShiftExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.ShiftExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShiftExpr([NotNull] Python3Parser.ShiftExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.ArithExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArithExpr([NotNull] Python3Parser.ArithExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.ArithExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArithExpr([NotNull] Python3Parser.ArithExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.Term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm([NotNull] Python3Parser.TermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.Term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm([NotNull] Python3Parser.TermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.Factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactor([NotNull] Python3Parser.FactorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.Factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactor([NotNull] Python3Parser.FactorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.Power"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPower([NotNull] Python3Parser.PowerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.Power"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPower([NotNull] Python3Parser.PowerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.AtomExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtomExpr([NotNull] Python3Parser.AtomExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.AtomExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtomExpr([NotNull] Python3Parser.AtomExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.Atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtom([NotNull] Python3Parser.AtomContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.Atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtom([NotNull] Python3Parser.AtomContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.TestlistComp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTestlistComp([NotNull] Python3Parser.TestlistCompContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.TestlistComp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTestlistComp([NotNull] Python3Parser.TestlistCompContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.TestlistCompSingle"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTestlistCompSingle([NotNull] Python3Parser.TestlistCompSingleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.TestlistCompSingle"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTestlistCompSingle([NotNull] Python3Parser.TestlistCompSingleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.TestlistCompLambda"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTestlistCompLambda([NotNull] Python3Parser.TestlistCompLambdaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.TestlistCompLambda"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTestlistCompLambda([NotNull] Python3Parser.TestlistCompLambdaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.TestlistCompArray"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTestlistCompArray([NotNull] Python3Parser.TestlistCompArrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.TestlistCompArray"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTestlistCompArray([NotNull] Python3Parser.TestlistCompArrayContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.Trailer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTrailer([NotNull] Python3Parser.TrailerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.Trailer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTrailer([NotNull] Python3Parser.TrailerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.SubscriptList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubscriptList([NotNull] Python3Parser.SubscriptListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.SubscriptList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubscriptList([NotNull] Python3Parser.SubscriptListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.Subscript"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubscript([NotNull] Python3Parser.SubscriptContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.Subscript"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubscript([NotNull] Python3Parser.SubscriptContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.SliceOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSliceOp([NotNull] Python3Parser.SliceOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.SliceOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSliceOp([NotNull] Python3Parser.SliceOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.ExprList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprList([NotNull] Python3Parser.ExprListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.ExprList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprList([NotNull] Python3Parser.ExprListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.TestList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTestList([NotNull] Python3Parser.TestListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.TestList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTestList([NotNull] Python3Parser.TestListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.DictOrSetMaker"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDictOrSetMaker([NotNull] Python3Parser.DictOrSetMakerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.DictOrSetMaker"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDictOrSetMaker([NotNull] Python3Parser.DictOrSetMakerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.ClassDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassDef([NotNull] Python3Parser.ClassDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.ClassDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassDef([NotNull] Python3Parser.ClassDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.ArgList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgList([NotNull] Python3Parser.ArgListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.ArgList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgList([NotNull] Python3Parser.ArgListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.Argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgument([NotNull] Python3Parser.ArgumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.Argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgument([NotNull] Python3Parser.ArgumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.CompIter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompIter([NotNull] Python3Parser.CompIterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.CompIter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompIter([NotNull] Python3Parser.CompIterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.CompFor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompFor([NotNull] Python3Parser.CompForContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.CompFor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompFor([NotNull] Python3Parser.CompForContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.CompIf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompIf([NotNull] Python3Parser.CompIfContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.CompIf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompIf([NotNull] Python3Parser.CompIfContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.EncodingDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEncodingDecl([NotNull] Python3Parser.EncodingDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.EncodingDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEncodingDecl([NotNull] Python3Parser.EncodingDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.YieldExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterYieldExpr([NotNull] Python3Parser.YieldExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.YieldExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitYieldExpr([NotNull] Python3Parser.YieldExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.YieldArg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterYieldArg([NotNull] Python3Parser.YieldArgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.YieldArg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitYieldArg([NotNull] Python3Parser.YieldArgContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace Antlr4.Grammar.Python
