//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\namofun\plagiarism\src\Plag.Frontend.Python\Python3.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Antlr4.Grammar.Python {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="Python3Parser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
//[System.CLSCompliant(false)]
public interface IPython3Listener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.SingleInput"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSingleInput([NotNull] Python3Parser.SingleInputContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.SingleInput"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSingleInput([NotNull] Python3Parser.SingleInputContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.FileInput"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFileInput([NotNull] Python3Parser.FileInputContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.FileInput"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFileInput([NotNull] Python3Parser.FileInputContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.EvalInput"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEvalInput([NotNull] Python3Parser.EvalInputContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.EvalInput"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEvalInput([NotNull] Python3Parser.EvalInputContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.Decorator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDecorator([NotNull] Python3Parser.DecoratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.Decorator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDecorator([NotNull] Python3Parser.DecoratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.Decorators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDecorators([NotNull] Python3Parser.DecoratorsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.Decorators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDecorators([NotNull] Python3Parser.DecoratorsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.Decorated"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDecorated([NotNull] Python3Parser.DecoratedContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.Decorated"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDecorated([NotNull] Python3Parser.DecoratedContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.AsyncFuncDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAsyncFuncDef([NotNull] Python3Parser.AsyncFuncDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.AsyncFuncDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAsyncFuncDef([NotNull] Python3Parser.AsyncFuncDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.Funcdef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncdef([NotNull] Python3Parser.FuncdefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.Funcdef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncdef([NotNull] Python3Parser.FuncdefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.Parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameters([NotNull] Python3Parser.ParametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.Parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameters([NotNull] Python3Parser.ParametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.Typedargslist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypedargslist([NotNull] Python3Parser.TypedargslistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.Typedargslist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypedargslist([NotNull] Python3Parser.TypedargslistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.Tfpdef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTfpdef([NotNull] Python3Parser.TfpdefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.Tfpdef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTfpdef([NotNull] Python3Parser.TfpdefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.Varargslist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarargslist([NotNull] Python3Parser.VarargslistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.Varargslist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarargslist([NotNull] Python3Parser.VarargslistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.Vfpdef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVfpdef([NotNull] Python3Parser.VfpdefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.Vfpdef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVfpdef([NotNull] Python3Parser.VfpdefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.Stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmt([NotNull] Python3Parser.StmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.Stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmt([NotNull] Python3Parser.StmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.SimpleStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleStmt([NotNull] Python3Parser.SimpleStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.SimpleStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleStmt([NotNull] Python3Parser.SimpleStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.SmallStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSmallStmt([NotNull] Python3Parser.SmallStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.SmallStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSmallStmt([NotNull] Python3Parser.SmallStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.ExprStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprStmt([NotNull] Python3Parser.ExprStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.ExprStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprStmt([NotNull] Python3Parser.ExprStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.AnnAssign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnnAssign([NotNull] Python3Parser.AnnAssignContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.AnnAssign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnnAssign([NotNull] Python3Parser.AnnAssignContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.TestlistStarExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTestlistStarExpr([NotNull] Python3Parser.TestlistStarExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.TestlistStarExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTestlistStarExpr([NotNull] Python3Parser.TestlistStarExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.AugAssign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAugAssign([NotNull] Python3Parser.AugAssignContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.AugAssign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAugAssign([NotNull] Python3Parser.AugAssignContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.DelStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDelStmt([NotNull] Python3Parser.DelStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.DelStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDelStmt([NotNull] Python3Parser.DelStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.PassStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPassStmt([NotNull] Python3Parser.PassStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.PassStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPassStmt([NotNull] Python3Parser.PassStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.FlowStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFlowStmt([NotNull] Python3Parser.FlowStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.FlowStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFlowStmt([NotNull] Python3Parser.FlowStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.BreakStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBreakStmt([NotNull] Python3Parser.BreakStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.BreakStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBreakStmt([NotNull] Python3Parser.BreakStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.ContinueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContinueStmt([NotNull] Python3Parser.ContinueStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.ContinueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContinueStmt([NotNull] Python3Parser.ContinueStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.ReturnStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnStmt([NotNull] Python3Parser.ReturnStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.ReturnStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnStmt([NotNull] Python3Parser.ReturnStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.YieldStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterYieldStmt([NotNull] Python3Parser.YieldStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.YieldStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitYieldStmt([NotNull] Python3Parser.YieldStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.RaiseStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRaiseStmt([NotNull] Python3Parser.RaiseStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.RaiseStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRaiseStmt([NotNull] Python3Parser.RaiseStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.ImportStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImportStmt([NotNull] Python3Parser.ImportStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.ImportStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImportStmt([NotNull] Python3Parser.ImportStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.ImportName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImportName([NotNull] Python3Parser.ImportNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.ImportName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImportName([NotNull] Python3Parser.ImportNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.ImportFrom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImportFrom([NotNull] Python3Parser.ImportFromContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.ImportFrom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImportFrom([NotNull] Python3Parser.ImportFromContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.ImportAsName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImportAsName([NotNull] Python3Parser.ImportAsNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.ImportAsName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImportAsName([NotNull] Python3Parser.ImportAsNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.DottedAsName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDottedAsName([NotNull] Python3Parser.DottedAsNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.DottedAsName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDottedAsName([NotNull] Python3Parser.DottedAsNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.ImportAsNames"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImportAsNames([NotNull] Python3Parser.ImportAsNamesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.ImportAsNames"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImportAsNames([NotNull] Python3Parser.ImportAsNamesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.DottedAsNames"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDottedAsNames([NotNull] Python3Parser.DottedAsNamesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.DottedAsNames"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDottedAsNames([NotNull] Python3Parser.DottedAsNamesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.DottedName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDottedName([NotNull] Python3Parser.DottedNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.DottedName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDottedName([NotNull] Python3Parser.DottedNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.GlobalStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGlobalStmt([NotNull] Python3Parser.GlobalStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.GlobalStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGlobalStmt([NotNull] Python3Parser.GlobalStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.NonLocalStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNonLocalStmt([NotNull] Python3Parser.NonLocalStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.NonLocalStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNonLocalStmt([NotNull] Python3Parser.NonLocalStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.AssertStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssertStmt([NotNull] Python3Parser.AssertStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.AssertStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssertStmt([NotNull] Python3Parser.AssertStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.CompoundStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompoundStmt([NotNull] Python3Parser.CompoundStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.CompoundStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompoundStmt([NotNull] Python3Parser.CompoundStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.AsyncStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAsyncStmt([NotNull] Python3Parser.AsyncStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.AsyncStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAsyncStmt([NotNull] Python3Parser.AsyncStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.IfStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStmt([NotNull] Python3Parser.IfStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.IfStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStmt([NotNull] Python3Parser.IfStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.WhileStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileStmt([NotNull] Python3Parser.WhileStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.WhileStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileStmt([NotNull] Python3Parser.WhileStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.ForStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForStmt([NotNull] Python3Parser.ForStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.ForStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForStmt([NotNull] Python3Parser.ForStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.TryStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTryStmt([NotNull] Python3Parser.TryStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.TryStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTryStmt([NotNull] Python3Parser.TryStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.WithStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWithStmt([NotNull] Python3Parser.WithStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.WithStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWithStmt([NotNull] Python3Parser.WithStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.WithItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWithItem([NotNull] Python3Parser.WithItemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.WithItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWithItem([NotNull] Python3Parser.WithItemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.ExceptClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExceptClause([NotNull] Python3Parser.ExceptClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.ExceptClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExceptClause([NotNull] Python3Parser.ExceptClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.Suite"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSuite([NotNull] Python3Parser.SuiteContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.Suite"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSuite([NotNull] Python3Parser.SuiteContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.Test"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTest([NotNull] Python3Parser.TestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.Test"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTest([NotNull] Python3Parser.TestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.TestNoCond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTestNoCond([NotNull] Python3Parser.TestNoCondContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.TestNoCond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTestNoCond([NotNull] Python3Parser.TestNoCondContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.Lambdef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLambdef([NotNull] Python3Parser.LambdefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.Lambdef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLambdef([NotNull] Python3Parser.LambdefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.LambdefNoCond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLambdefNoCond([NotNull] Python3Parser.LambdefNoCondContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.LambdefNoCond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLambdefNoCond([NotNull] Python3Parser.LambdefNoCondContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.OrTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrTest([NotNull] Python3Parser.OrTestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.OrTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrTest([NotNull] Python3Parser.OrTestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.AndTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAndTest([NotNull] Python3Parser.AndTestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.AndTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAndTest([NotNull] Python3Parser.AndTestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.NotTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNotTest([NotNull] Python3Parser.NotTestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.NotTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNotTest([NotNull] Python3Parser.NotTestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.Comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparison([NotNull] Python3Parser.ComparisonContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.Comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparison([NotNull] Python3Parser.ComparisonContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.CompOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompOp([NotNull] Python3Parser.CompOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.CompOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompOp([NotNull] Python3Parser.CompOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.StarExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStarExpr([NotNull] Python3Parser.StarExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.StarExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStarExpr([NotNull] Python3Parser.StarExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.Expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] Python3Parser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.Expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] Python3Parser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.XorExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterXorExpr([NotNull] Python3Parser.XorExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.XorExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitXorExpr([NotNull] Python3Parser.XorExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.AndExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAndExpr([NotNull] Python3Parser.AndExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.AndExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAndExpr([NotNull] Python3Parser.AndExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.ShiftExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShiftExpr([NotNull] Python3Parser.ShiftExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.ShiftExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShiftExpr([NotNull] Python3Parser.ShiftExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.ArithExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArithExpr([NotNull] Python3Parser.ArithExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.ArithExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArithExpr([NotNull] Python3Parser.ArithExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.Term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerm([NotNull] Python3Parser.TermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.Term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerm([NotNull] Python3Parser.TermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.Factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactor([NotNull] Python3Parser.FactorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.Factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactor([NotNull] Python3Parser.FactorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.Power"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPower([NotNull] Python3Parser.PowerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.Power"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPower([NotNull] Python3Parser.PowerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.AtomExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtomExpr([NotNull] Python3Parser.AtomExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.AtomExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtomExpr([NotNull] Python3Parser.AtomExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.Atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtom([NotNull] Python3Parser.AtomContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.Atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtom([NotNull] Python3Parser.AtomContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.TestlistComp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTestlistComp([NotNull] Python3Parser.TestlistCompContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.TestlistComp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTestlistComp([NotNull] Python3Parser.TestlistCompContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.TestlistCompSingle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTestlistCompSingle([NotNull] Python3Parser.TestlistCompSingleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.TestlistCompSingle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTestlistCompSingle([NotNull] Python3Parser.TestlistCompSingleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.TestlistCompLambda"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTestlistCompLambda([NotNull] Python3Parser.TestlistCompLambdaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.TestlistCompLambda"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTestlistCompLambda([NotNull] Python3Parser.TestlistCompLambdaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.TestlistCompArray"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTestlistCompArray([NotNull] Python3Parser.TestlistCompArrayContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.TestlistCompArray"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTestlistCompArray([NotNull] Python3Parser.TestlistCompArrayContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.Trailer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTrailer([NotNull] Python3Parser.TrailerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.Trailer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTrailer([NotNull] Python3Parser.TrailerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.SubscriptList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubscriptList([NotNull] Python3Parser.SubscriptListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.SubscriptList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubscriptList([NotNull] Python3Parser.SubscriptListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.Subscript"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubscript([NotNull] Python3Parser.SubscriptContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.Subscript"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubscript([NotNull] Python3Parser.SubscriptContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.SliceOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSliceOp([NotNull] Python3Parser.SliceOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.SliceOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSliceOp([NotNull] Python3Parser.SliceOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.ExprList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprList([NotNull] Python3Parser.ExprListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.ExprList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprList([NotNull] Python3Parser.ExprListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.TestList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTestList([NotNull] Python3Parser.TestListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.TestList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTestList([NotNull] Python3Parser.TestListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.DictOrSetMaker"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDictOrSetMaker([NotNull] Python3Parser.DictOrSetMakerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.DictOrSetMaker"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDictOrSetMaker([NotNull] Python3Parser.DictOrSetMakerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.ClassDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassDef([NotNull] Python3Parser.ClassDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.ClassDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassDef([NotNull] Python3Parser.ClassDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.ArgList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgList([NotNull] Python3Parser.ArgListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.ArgList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgList([NotNull] Python3Parser.ArgListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.Argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgument([NotNull] Python3Parser.ArgumentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.Argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgument([NotNull] Python3Parser.ArgumentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.CompIter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompIter([NotNull] Python3Parser.CompIterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.CompIter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompIter([NotNull] Python3Parser.CompIterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.CompFor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompFor([NotNull] Python3Parser.CompForContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.CompFor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompFor([NotNull] Python3Parser.CompForContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.CompIf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompIf([NotNull] Python3Parser.CompIfContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.CompIf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompIf([NotNull] Python3Parser.CompIfContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.EncodingDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEncodingDecl([NotNull] Python3Parser.EncodingDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.EncodingDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEncodingDecl([NotNull] Python3Parser.EncodingDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.YieldExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterYieldExpr([NotNull] Python3Parser.YieldExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.YieldExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitYieldExpr([NotNull] Python3Parser.YieldExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.YieldArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterYieldArg([NotNull] Python3Parser.YieldArgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.YieldArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitYieldArg([NotNull] Python3Parser.YieldArgContext context);
}
} // namespace Antlr4.Grammar.Python
